name: Test Build
on: push

jobs:
  main:
    name: Build using PlatformIO
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.x'
      - name: Install PlatformIO
        run: |
          python -m pip install --upgrade pip
          pip install -U platformio
      - name: Build Firmware
        run: platformio run
